### PR TITLE
Latest changes

### PR DESCRIPTION
**Pull request by majkinetor**

### CODE REVIEW

**Comment by majkinetor** [comment]
I didn't notice that PR automatically adds new commits at later date. Sorry for two aditional PRs.

**Comment by ferventcoder** [comment]
That is why typically you want to use feature branches for PRs and not the same branch.

**Comment by majkinetor** [comment]
I got it now... anyway,  all commits in master are to be included.

I will do future patches in separate branch.

**Comment by ferventcoder** [comment]
Merged into master at https://github.com/chocolatey/chocolatey-packages-template/commit/6dcbed0d4c817e087b001e09e3f2ba89753edcf2

**Pull request closed without merging**
