### PR TITLE
Moved checksumType variables' definition to setting for Ketarin

### PR DESCRIPTION
**Pull request by Elderry**

### CODE REVIEW

**Comment by ferventcoder** [comment]
Unfortunately this change is not quite complete. If you are going to change the ability to pass in your own checksum type, you need to edit the ketarin settings c# to pivot on that value and calculate the proper checksum. Right now it only calculates on sha256.

**Comment by Elderry** [comment]
I've noticed that the ketarin's C# setting only calculates sha256, and now I just want to move the definition of checksum type variable from chocolateyInstall.ps1 to the package's ketarin setting.

**Comment by ferventcoder** [comment]
Yes, but you can't do that without also fixing up the c# code in the ketarin settings file to allow for it to receive other types.

**Comment by ferventcoder** [comment]
HTH

**Comment by Elderry** [comment]
Now I have turned to AU so I won't continue this improve.

**Comment by gep13** [comment]
>@Elderry said...
Now I have turned to AU so I won't continue this improve.

Thanks! If you can offer any help in porting to AU, we would appreciate it 👍

**Pull request closed without merging**
